theme: jekyll-theme-minimal
title: Savarankiškos pseudonimizuotos tapatybės valdymo sistema
description: Baigiamasis magistrinis darbas
logo: https://media.licdn.com/dms/image/v2/D4E03AQFM33iT233F7A/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1693165148573?e=1739404800&v=beta&t=mGCCcTAah5uIRQ7BEDkfnDJFQNUzWL2tiUhMIY1s_xY
show_downloads: false
