theme: jekyll-theme-minimal
title: Savarankiškos pseudonimizuotos tapatybės valdymo sistema
description: Magistro projekto informacinė sistema
logo: https://media.licdn.com/dms/image/v2/D4E12AQFZdLnh0M8IHA/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1732484296371?e=2147483647&v=beta&t=Yl4_9J-oKgfLZ1U6h-UsDGgQotkf8DFMy17dr2EF9YY
show_downloads: false
